"""add month to reports

Revision ID: c70e0384b526
Revises: 362b7bbc2a50
Create Date: 2025-04-13 10:34:04.148897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c70e0384b526'
down_revision: Union[str, None] = '362b7bbc2a50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('month', sa.Integer(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'month')
    # ### end Alembic commands ###
